# Generated by Django 3.1.7 on 2021-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
